CREATE TABLE PACIENTES (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    EDAD NUMBER(3),
    GENERO VARCHAR2(10),
    TELEFONO VARCHAR2(20),
    DIRECCION VARCHAR2(200),
    FECHA_REGISTRO TIMESTAMP DEFAULT SYSTIMESTAMP
);
